parameters:
    database_host:     127.0.0.1
    database_port:     3306
    database_name:     prestashop
    database_user:     root
    database_password: root
    database_prefix:   ps_
    database_engine: InnoDB
    # You should uncomment this if you want use pdo_sqlite
    # database_path: "%kernel.root_dir%/data.db3"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret: ThisTokenIsNotSoSecretChangeIt
    ps_caching: CacheMemcache
    ps_cache_enable: false
    ps_creation_date: ~
    locale: en-US
